import type { DataDomain, DataMeshGovernance, DomainRelationship } from '@/types/data-mesh';

export const mockDataDomains: DataDomain[] = [
  {
    id: 'domain-001',
    name: 'Platform & Infrastructure',
    description: 'Core data platform services, user events, and infrastructure',
    owner: 'sarah.chen@company.com',
    ownerTeam: 'data-platform',
    status: 'active',
    color: '#3b82f6',
    datasets: 45,
    pipelines: 18,
    consumers: 12,
    dataProducts: [
      {
        id: 'dp-001',
        name: 'User Events Stream',
        description: 'Real-time user activity events from all platforms',
        type: 'dataset',
        owner: 'sarah.chen@company.com',
        status: 'active',
        version: '2.3.0',
        sla: { availability: 99.95, freshness: 'real-time', support: '24/7' },
        consumers: [
          { id: 'c-001', name: 'Analytics Dashboard', team: 'analytics', type: 'internal', usage: { queriesPerDay: 5000, dataVolumeGB: 150 } },
          { id: 'c-002', name: 'ML Feature Store', team: 'ml-platform', type: 'internal', usage: { queriesPerDay: 2500, dataVolumeGB: 75 } },
          { id: 'c-003', name: 'Customer 360 API', team: 'platform', type: 'internal', usage: { queriesPerDay: 10000, dataVolumeGB: 300 } },
        ],
        tags: ['events', 'real-time', 'core'],
      },
      {
        id: 'dp-002',
        name: 'Customer Profile API',
        description: 'Unified customer profile with 360° view',
        type: 'api',
        owner: 'sarah.chen@company.com',
        status: 'active',
        version: '1.8.0',
        sla: { availability: 99.9, freshness: '5 minutes', support: '24/7' },
        consumers: [
          { id: 'c-004', name: 'Mobile App', team: 'mobile', type: 'internal', usage: { queriesPerDay: 50000, dataVolumeGB: 50 } },
          { id: 'c-005', name: 'Web App', team: 'web', type: 'internal', usage: { queriesPerDay: 75000, dataVolumeGB: 75 } },
        ],
        tags: ['api', 'customer', 'core'],
      },
      {
        id: 'dp-003',
        name: 'Data Quality Metrics',
        description: 'Data quality scores and validation results',
        type: 'dashboard',
        owner: 'sarah.chen@company.com',
        status: 'active',
        version: '1.2.0',
        sla: { availability: 99.5, freshness: '1 hour', support: 'business-hours' },
        consumers: [
          { id: 'c-006', name: 'Data Governance Team', team: 'governance', type: 'internal', usage: { queriesPerDay: 100, dataVolumeGB: 1 } },
        ],
        tags: ['quality', 'governance'],
      },
    ],
    governance: {
      dataQualityScore: 96,
      documentationCoverage: 92,
      lastAuditDate: '2024-08-15',
      complianceStatus: 'compliant',
    },
    metrics: {
      totalStorageGB: 4500,
      monthlyQueryVolume: 2500000,
      uptimePercentage: 99.95,
      dataFreshness: 2,
    },
  },
  {
    id: 'domain-002',
    name: 'Finance & Revenue',
    description: 'Financial data, revenue reporting, and payment processing',
    owner: 'mike.rodriguez@company.com',
    ownerTeam: 'finance-data',
    status: 'active',
    color: '#10b981',
    datasets: 28,
    pipelines: 12,
    consumers: 8,
    dataProducts: [
      {
        id: 'dp-004',
        name: 'Revenue Dashboard',
        description: 'Executive revenue and financial KPIs',
        type: 'dashboard',
        owner: 'mike.rodriguez@company.com',
        status: 'active',
        version: '3.1.0',
        sla: { availability: 99.9, freshness: '1 hour', support: 'business-hours' },
        consumers: [
          { id: 'c-007', name: 'Executive Team', team: 'executive', type: 'internal', usage: { queriesPerDay: 50, dataVolumeGB: 0.5 } },
          { id: 'c-008', name: 'Finance Team', team: 'finance', type: 'internal', usage: { queriesPerDay: 500, dataVolumeGB: 2 } },
        ],
        tags: ['revenue', 'executive', 'finance'],
      },
      {
        id: 'dp-005',
        name: 'Revenue Data API',
        description: 'Revenue and transaction data for integrations',
        type: 'api',
        owner: 'mike.rodriguez@company.com',
        status: 'active',
        version: '2.0.0',
        sla: { availability: 99.95, freshness: '15 minutes', support: '24/7' },
        consumers: [
          { id: 'c-009', name: 'ERP Integration', team: 'finance', type: 'internal', usage: { queriesPerDay: 1000, dataVolumeGB: 5 } },
          { id: 'c-010', name: 'External Reporting', team: 'external', type: 'external', usage: { queriesPerDay: 200, dataVolumeGB: 1 } },
        ],
        tags: ['api', 'revenue', 'integration'],
      },
    ],
    governance: {
      dataQualityScore: 98,
      documentationCoverage: 95,
      lastAuditDate: '2024-08-20',
      complianceStatus: 'compliant',
    },
    metrics: {
      totalStorageGB: 850,
      monthlyQueryVolume: 15000,
      uptimePercentage: 99.9,
      dataFreshness: 15,
    },
  },
  {
    id: 'domain-003',
    name: 'Machine Learning',
    description: 'ML models, features, predictions, and model performance',
    owner: 'alex.kumar@company.com',
    ownerTeam: 'ml-platform',
    status: 'active',
    color: '#8b5cf6',
    datasets: 35,
    pipelines: 15,
    consumers: 10,
    dataProducts: [
      {
        id: 'dp-006',
        name: 'Customer Segmentation Model',
        description: 'ML model for customer segmentation with 8 segments',
        type: 'ml-model',
        owner: 'alex.kumar@company.com',
        status: 'active',
        version: '2.5.0',
        sla: { availability: 99.5, freshness: '24 hours', support: 'business-hours' },
        consumers: [
          { id: 'c-011', name: 'Marketing Automation', team: 'marketing', type: 'internal', usage: { queriesPerDay: 500, dataVolumeGB: 10 } },
          { id: 'c-012', name: 'Personalization Engine', team: 'product', type: 'internal', usage: { queriesPerDay: 10000, dataVolumeGB: 50 } },
        ],
        tags: ['ml', 'segmentation', 'customer'],
      },
      {
        id: 'dp-007',
        name: 'Feature Store',
        description: 'ML features for real-time inference',
        type: 'dataset',
        owner: 'alex.kumar@company.com',
        status: 'active',
        version: '1.9.0',
        sla: { availability: 99.9, freshness: '5 minutes', support: '24/7' },
        consumers: [
          { id: 'c-013', name: 'Recommendation API', team: 'ml-platform', type: 'internal', usage: { queriesPerDay: 50000, dataVolumeGB: 100 } },
          { id: 'c-014', name: 'Fraud Detection', team: 'security', type: 'internal', usage: { queriesPerDay: 100000, dataVolumeGB: 200 } },
        ],
        tags: ['ml', 'features', 'real-time'],
      },
      {
        id: 'dp-008',
        name: 'Model Performance Dashboard',
        description: 'ML model monitoring and drift detection',
        type: 'dashboard',
        owner: 'alex.kumar@company.com',
        status: 'active',
        version: '1.5.0',
        sla: { availability: 99.5, freshness: '15 minutes', support: 'business-hours' },
        consumers: [
          { id: 'c-015', name: 'ML Engineers', team: 'ml-platform', type: 'internal', usage: { queriesPerDay: 200, dataVolumeGB: 2 } },
        ],
        tags: ['ml', 'monitoring', 'observability'],
      },
    ],
    governance: {
      dataQualityScore: 94,
      documentationCoverage: 88,
      lastAuditDate: '2024-08-10',
      complianceStatus: 'compliant',
    },
    metrics: {
      totalStorageGB: 2200,
      monthlyQueryVolume: 4500000,
      uptimePercentage: 99.8,
      dataFreshness: 5,
    },
  },
  {
    id: 'domain-004',
    name: 'Operations & Logistics',
    description: 'Inventory, warehouse, and supply chain data',
    owner: 'jessica.lee@company.com',
    ownerTeam: 'ops-data',
    status: 'active',
    color: '#f59e0b',
    datasets: 22,
    pipelines: 10,
    consumers: 6,
    dataProducts: [
      {
        id: 'dp-009',
        name: 'Real-time Inventory',
        description: 'Live inventory levels across all warehouses',
        type: 'dataset',
        owner: 'jessica.lee@company.com',
        status: 'active',
        version: '2.0.0',
        sla: { availability: 99.95, freshness: '1 minute', support: '24/7' },
        consumers: [
          { id: 'c-016', name: 'Inventory Dashboard', team: 'operations', type: 'internal', usage: { queriesPerDay: 10000, dataVolumeGB: 20 } },
          { id: 'c-017', name: 'E-commerce Platform', team: 'ecommerce', type: 'internal', usage: { queriesPerDay: 50000, dataVolumeGB: 30 } },
        ],
        tags: ['inventory', 'real-time', 'operations'],
      },
      {
        id: 'dp-010',
        name: 'Supply Chain Analytics',
        description: 'Supply chain performance and optimization metrics',
        type: 'dashboard',
        owner: 'jessica.lee@company.com',
        status: 'active',
        version: '1.3.0',
        sla: { availability: 99.5, freshness: '1 hour', support: 'business-hours' },
        consumers: [
          { id: 'c-018', name: 'Ops Team', team: 'operations', type: 'internal', usage: { queriesPerDay: 200, dataVolumeGB: 5 } },
        ],
        tags: ['supply-chain', 'analytics'],
      },
    ],
    governance: {
      dataQualityScore: 97,
      documentationCoverage: 90,
      lastAuditDate: '2024-08-25',
      complianceStatus: 'compliant',
    },
    metrics: {
      totalStorageGB: 650,
      monthlyQueryVolume: 850000,
      uptimePercentage: 99.95,
      dataFreshness: 1,
    },
  },
  {
    id: 'domain-005',
    name: 'Product & Catalog',
    description: 'Product catalog, pricing, and product analytics',
    owner: 'david.park@company.com',
    ownerTeam: 'product-data',
    status: 'active',
    color: '#ec4899',
    datasets: 18,
    pipelines: 8,
    consumers: 9,
    dataProducts: [
      {
        id: 'dp-011',
        name: 'Product Catalog API',
        description: 'Complete product catalog with attributes and pricing',
        type: 'api',
        owner: 'david.park@company.com',
        status: 'active',
        version: '3.2.0',
        sla: { availability: 99.9, freshness: '5 minutes', support: '24/7' },
        consumers: [
          { id: 'c-019', name: 'E-commerce Platform', team: 'ecommerce', type: 'internal', usage: { queriesPerDay: 100000, dataVolumeGB: 150 } },
          { id: 'c-020', name: 'Mobile App', team: 'mobile', type: 'internal', usage: { queriesPerDay: 75000, dataVolumeGB: 100 } },
          { id: 'c-021', name: 'Partner API', team: 'external', type: 'external', usage: { queriesPerDay: 5000, dataVolumeGB: 25 } },
        ],
        tags: ['api', 'catalog', 'product'],
      },
      {
        id: 'dp-012',
        name: 'Product Analytics',
        description: 'Product performance and analytics dashboard',
        type: 'dashboard',
        owner: 'david.park@company.com',
        status: 'active',
        version: '2.1.0',
        sla: { availability: 99.5, freshness: '1 hour', support: 'business-hours' },
        consumers: [
          { id: 'c-022', name: 'Product Managers', team: 'product', type: 'internal', usage: { queriesPerDay: 300, dataVolumeGB: 3 } },
        ],
        tags: ['analytics', 'product'],
      },
    ],
    governance: {
      dataQualityScore: 93,
      documentationCoverage: 85,
      lastAuditDate: '2024-08-05',
      complianceStatus: 'compliant',
    },
    metrics: {
      totalStorageGB: 420,
      monthlyQueryVolume: 1200000,
      uptimePercentage: 99.9,
      dataFreshness: 5,
    },
  },
];

export const mockDataMeshGovernance: DataMeshGovernance = {
  domains: 5,
  dataProducts: 12,
  totalDatasets: 148,
  federatedGovernance: true,
  standards: {
    documentation: 90,
    dataQuality: 96,
    metadata: 88,
    accessControl: 95,
  },
};

export const mockDomainRelationships: DomainRelationship[] = [
  { source: 'domain-001', target: 'domain-002', relationship: 'produces-for', dataVolumeGB: 150 },
  { source: 'domain-001', target: 'domain-003', relationship: 'produces-for', dataVolumeGB: 450 },
  { source: 'domain-002', target: 'domain-001', relationship: 'shares-with', dataVolumeGB: 50 },
  { source: 'domain-003', target: 'domain-001', relationship: 'depends-on', dataVolumeGB: 200 },
  { source: 'domain-003', target: 'domain-002', relationship: 'produces-for', dataVolumeGB: 25 },
  { source: 'domain-004', target: 'domain-001', relationship: 'produces-for', dataVolumeGB: 80 },
  { source: 'domain-005', target: 'domain-004', relationship: 'shares-with', dataVolumeGB: 120 },
  { source: 'domain-005', target: 'domain-001', relationship: 'depends-on', dataVolumeGB: 200 },
];
