import type { QueryMetrics, QueryOptimization, TableStatistics, QueryPerformanceSummary } from '@/types/query-performance';

export const mockQueryMetrics: QueryMetrics[] = [
  {
    id: 'query-001',
    queryText: 'SELECT user_id, event_type, COUNT(*) FROM user_events WHERE event_date >= CURRENT_DATE - 30 GROUP BY user_id, event_type',
    normalizedQuery: 'SELECT user_id, event_type, COUNT(*) FROM user_events WHERE event_date >= ? GROUP BY user_id, event_type',
    status: 'completed',
    startedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    duration: 125000,
    user: 'data.analyst@company.com',
    team: 'analytics',
    warehouse: 'ANALYTICS_WH',
    database: 'ANALYTICS',
    schema: 'PROD',
    tables: ['user_events'],
    bytesScanned: 45200000000,
    rowsReturned: 150000,
    partitionsScanned: 30,
    partitionsTotal: 90,
    cachingUsed: false,
    complexity: 'moderate',
    cost: 2.85,
  },
  {
    id: 'query-002',
    queryText: 'SELECT * FROM revenue_daily WHERE date >= CURRENT_DATE - 7',
    normalizedQuery: 'SELECT * FROM revenue_daily WHERE date >= ?',
    status: 'completed',
    startedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
    duration: 45000,
    user: 'finance.user@company.com',
    team: 'finance',
    warehouse: 'FINANCE_WH',
    database: 'FINANCE',
    schema: 'PROD',
    tables: ['revenue_daily'],
    bytesScanned: 8500000000,
    rowsReturned: 7,
    partitionsScanned: 7,
    partitionsTotal: 7,
    cachingUsed: true,
    complexity: 'simple',
    cost: 0.45,
  },
  {
    id: 'query-003',
    queryText: 'SELECT customer_id, segment, predicted_ltv FROM ml_predictions WHERE model_version = 2.5',
    normalizedQuery: 'SELECT customer_id, segment, predicted_ltv FROM ml_predictions WHERE model_version = ?',
    status: 'completed',
    startedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 52).toISOString(),
    duration: 485000,
    user: 'ml.engineer@company.com',
    team: 'ml-platform',
    warehouse: 'ML_WH',
    database: 'ML',
    schema: 'PROD',
    tables: ['ml_predictions', 'customer_features'],
    bytesScanned: 180000000000,
    rowsReturned: 2500000,
    partitionsScanned: 45,
    partitionsTotal: 45,
    cachingUsed: false,
    complexity: 'complex',
    cost: 12.50,
  },
  {
    id: 'query-004',
    queryText: 'SELECT product_id, inventory_count FROM inventory WHERE warehouse_id = 5',
    normalizedQuery: 'SELECT product_id, inventory_count FROM inventory WHERE warehouse_id = ?',
    status: 'running',
    startedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    duration: 300000,
    user: 'ops.user@company.com',
    team: 'operations',
    warehouse: 'OPS_WH',
    database: 'OPERATIONS',
    schema: 'PROD',
    tables: ['inventory'],
    bytesScanned: 2200000000,
    rowsReturned: 0,
    partitionsScanned: 1,
    partitionsTotal: 50,
    cachingUsed: false,
    complexity: 'simple',
    cost: 0.85,
  },
  {
    id: 'query-005',
    queryText: 'SELECT sku, name, category, price FROM products p JOIN categories c ON p.category_id = c.id WHERE p.updated_at > CURRENT_DATE - 1',
    normalizedQuery: 'SELECT sku, name, category, price FROM products p JOIN categories c ON p.category_id = c.id WHERE p.updated_at > ?',
    status: 'completed',
    startedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 119).toISOString(),
    duration: 180000,
    user: 'product.analyst@company.com',
    team: 'product',
    warehouse: 'PRODUCT_WH',
    database: 'PRODUCT',
    schema: 'PROD',
    tables: ['products', 'categories'],
    bytesScanned: 8800000000,
    rowsReturned: 25000,
    partitionsScanned: 1,
    partitionsTotal: 30,
    cachingUsed: false,
    complexity: 'moderate',
    cost: 2.10,
  },
  {
    id: 'query-006',
    queryText: 'SELECT * FROM large_table ORDER BY timestamp DESC LIMIT 1000000',
    normalizedQuery: 'SELECT * FROM large_table ORDER BY timestamp DESC LIMIT ?',
    status: 'completed',
    startedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 175).toISOString(),
    duration: 320000,
    user: 'data.analyst@company.com',
    team: 'analytics',
    warehouse: 'ANALYTICS_WH',
    database: 'ANALYTICS',
    schema: 'PROD',
    tables: ['large_table'],
    bytesScanned: 250000000000,
    rowsReturned: 1000000,
    partitionsScanned: 365,
    partitionsTotal: 365,
    cachingUsed: false,
    complexity: 'very_complex',
    cost: 15.60,
  },
  {
    id: 'query-007',
    queryText: 'SELECT user_id, session_count FROM user_sessions WHERE session_date = CURRENT_DATE',
    normalizedQuery: 'SELECT user_id, session_count FROM user_sessions WHERE session_date = ?',
    status: 'failed',
    startedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 239).toISOString(),
    duration: 60000,
    user: 'data.analyst@company.com',
    team: 'analytics',
    warehouse: 'ANALYTICS_WH',
    database: 'ANALYTICS',
    schema: 'PROD',
    tables: ['user_sessions'],
    bytesScanned: 5000000000,
    rowsReturned: 0,
    partitionsScanned: 1,
    partitionsTotal: 90,
    cachingUsed: false,
    complexity: 'simple',
    cost: 0.25,
    errorMessage: 'Table USER_SESSIONS does not exist',
  },
  {
    id: 'query-008',
    queryText: 'SELECT COUNT(DISTINCT user_id) FROM events WHERE event_type IN (purchase, add_to_cart) AND event_date >= CURRENT_DATE - 90',
    normalizedQuery: 'SELECT COUNT(DISTINCT user_id) FROM events WHERE event_type IN (...) AND event_date >= ?',
    status: 'queued',
    startedAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    duration: 0,
    user: 'marketing.analyst@company.com',
    team: 'marketing',
    warehouse: 'MARKETING_WH',
    database: 'ANALYTICS',
    schema: 'PROD',
    tables: ['events'],
    bytesScanned: 0,
    rowsReturned: 0,
    partitionsScanned: 0,
    partitionsTotal: 90,
    cachingUsed: false,
    complexity: 'complex',
    cost: 0,
  },
];

export const mockQueryOptimizations: QueryOptimization[] = [
  {
    queryId: 'query-001',
    issue: 'Missing partition pruning',
    severity: 'high',
    category: 'partition',
    suggestion: 'Add date filter to enable partition pruning',
    potentialImprovement: 'Reduce scan from 90 to 30 partitions (67% reduction)',
    estimatedCostSavings: 1.90,
  },
  {
    queryId: 'query-003',
    issue: 'Large table scan without clustering',
    severity: 'medium',
    category: 'partition',
    suggestion: 'Add clustering key on model_version column',
    potentialImprovement: 'Reduce scan time by 40%',
    estimatedCostSavings: 5.00,
  },
  {
    queryId: 'query-004',
    issue: 'No index on warehouse_id',
    severity: 'high',
    category: 'index',
    suggestion: 'Create index on warehouse_id column',
    potentialImprovement: 'Reduce query time from 5min to <10s',
    estimatedCostSavings: 0.75,
  },
  {
    queryId: 'query-005',
    issue: 'JOIN without proper filtering',
    severity: 'medium',
    category: 'join',
    suggestion: 'Add filter on categories table before joining',
    potentialImprovement: 'Reduce data processed by 60%',
    estimatedCostSavings: 1.26,
  },
  {
    queryId: 'query-006',
    issue: 'SELECT * with large LIMIT',
    severity: 'critical',
    category: 'filter',
    suggestion: 'Select only required columns and reduce LIMIT',
    potentialImprovement: 'Reduce from 250GB to 25GB scanned',
    estimatedCostSavings: 14.04,
  },
  {
    queryId: 'query-007',
    issue: 'Table not found - possible typo',
    severity: 'critical',
    category: 'filter',
    suggestion: 'Table name should be user_sessions_v2',
    potentialImprovement: 'Fix syntax error',
    estimatedCostSavings: 0,
  },
];

export const mockTableStatistics: TableStatistics[] = [
  {
    tableName: 'user_events',
    schema: 'PROD',
    database: 'ANALYTICS',
    rowCount: 2500000000,
    sizeGB: 450,
    lastUpdated: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    partitions: 90,
    clusteringKey: 'event_date',
    columns: [
      { name: 'user_id', type: 'VARCHAR', mode: 'required', nullPercentage: 0, cardinality: 50000000, distinctValues: 50000000, avgSizeBytes: 32 },
      { name: 'event_type', type: 'VARCHAR', mode: 'required', nullPercentage: 0, cardinality: 25, distinctValues: 25, avgSizeBytes: 16 },
      { name: 'event_date', type: 'DATE', mode: 'required', nullPercentage: 0, cardinality: 90, distinctValues: 90, avgSizeBytes: 4 },
      { name: 'properties', type: 'VARIANT', mode: 'nullable', nullPercentage: 5, cardinality: 2500000000, distinctValues: 2000000000, avgSizeBytes: 256 },
    ],
  },
  {
    tableName: 'revenue_daily',
    schema: 'PROD',
    database: 'FINANCE',
    rowCount: 730,
    sizeGB: 15,
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    partitions: 7,
    clusteringKey: 'date',
    columns: [
      { name: 'date', type: 'DATE', mode: 'required', nullPercentage: 0, cardinality: 730, distinctValues: 730, avgSizeBytes: 4 },
      { name: 'revenue', type: 'DECIMAL', mode: 'required', nullPercentage: 0, cardinality: 730, distinctValues: 730, avgSizeBytes: 16 },
      { name: 'currency', type: 'VARCHAR', mode: 'required', nullPercentage: 0, cardinality: 5, distinctValues: 5, avgSizeBytes: 3 },
    ],
  },
  {
    tableName: 'ml_predictions',
    schema: 'PROD',
    database: 'ML',
    rowCount: 2500000,
    sizeGB: 85,
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    partitions: 45,
    columns: [
      { name: 'customer_id', type: 'VARCHAR', mode: 'required', nullPercentage: 0, cardinality: 2500000, distinctValues: 2500000, avgSizeBytes: 32 },
      { name: 'segment', type: 'VARCHAR', mode: 'required', nullPercentage: 0, cardinality: 8, distinctValues: 8, avgSizeBytes: 12 },
      { name: 'predicted_ltv', type: 'DECIMAL', mode: 'required', nullPercentage: 0, cardinality: 2500000, distinctValues: 2450000, avgSizeBytes: 16 },
      { name: 'model_version', type: 'VARCHAR', mode: 'required', nullPercentage: 0, cardinality: 5, distinctValues: 5, avgSizeBytes: 8 },
    ],
  },
  {
    tableName: 'inventory',
    schema: 'PROD',
    database: 'OPERATIONS',
    rowCount: 500000,
    sizeGB: 8,
    lastUpdated: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    partitions: 50,
    columns: [
      { name: 'product_id', type: 'VARCHAR', mode: 'required', nullPercentage: 0, cardinality: 500000, distinctValues: 500000, avgSizeBytes: 16 },
      { name: 'warehouse_id', type: 'INTEGER', mode: 'required', nullPercentage: 0, cardinality: 50, distinctValues: 50, avgSizeBytes: 4 },
      { name: 'inventory_count', type: 'INTEGER', mode: 'required', nullPercentage: 0, cardinality: 10000, distinctValues: 10000, avgSizeBytes: 4 },
    ],
  },
];

export const mockQueryPerformanceSummary: QueryPerformanceSummary = {
  totalQueries: 1247,
  avgDuration: 85000,
  p95Duration: 245000,
  p99Duration: 485000,
  totalCost: 450.25,
  cacheHitRate: 35,
  slowQueries: 23,
};
