import type { SchemaRegistry, SchemaEvolution } from '@/types/schema-registry';

export const mockSchemaRegistries: SchemaRegistry[] = [
  {
    id: 'schema-001',
    name: 'User Events Schema',
    subject: 'user-events-value',
    description: 'Schema for user activity events from Kafka',
    owner: 'data-platform-team',
    team: 'platform',
    format: 'avro',
    currentVersion: 3,
    compatibility: 'backward',
    tags: ['events', 'user', 'kafka'],
    usage: {
      producers: 5,
      consumers: 12,
    },
    versions: [
      {
        id: 'ver-001-1',
        version: 1,
        createdAt: '2024-01-15T00:00:00Z',
        createdBy: 'john.doe@company.com',
        isActive: false,
        compatibility: 'backward',
        schema: [
          { name: 'user_id', type: 'string', mode: 'required', description: 'Unique user identifier' },
          { name: 'event_type', type: 'string', mode: 'required', description: 'Type of event' },
          { name: 'timestamp', type: 'long', mode: 'required', description: 'Unix timestamp' },
          { name: 'properties', type: 'map', mode: 'nullable', description: 'Event properties' },
        ],
        changeLog: [],
      },
      {
        id: 'ver-001-2',
        version: 2,
        createdAt: '2024-03-20T00:00:00Z',
        createdBy: 'jane.smith@company.com',
        isActive: false,
        compatibility: 'backward',
        schema: [
          { name: 'user_id', type: 'string', mode: 'required', description: 'Unique user identifier' },
          { name: 'event_type', type: 'string', mode: 'required', description: 'Type of event' },
          { name: 'timestamp', type: 'long', mode: 'required', description: 'Unix timestamp' },
          { name: 'properties', type: 'map', mode: 'nullable', description: 'Event properties' },
          { name: 'session_id', type: 'string', mode: 'nullable', description: 'Session identifier', defaultValue: null },
        ],
        changeLog: [
          { fieldName: 'session_id', changeType: 'added', isBreaking: false, description: 'Added session tracking' },
        ],
      },
      {
        id: 'ver-001-3',
        version: 3,
        createdAt: '2024-06-10T00:00:00Z',
        createdBy: 'bob.wilson@company.com',
        isActive: true,
        compatibility: 'backward',
        schema: [
          { name: 'user_id', type: 'string', mode: 'required', description: 'Unique user identifier' },
          { name: 'event_type', type: 'string', mode: 'required', description: 'Type of event' },
          { name: 'timestamp', type: 'long', mode: 'required', description: 'Unix timestamp' },
          { name: 'properties', type: 'map', mode: 'nullable', description: 'Event properties' },
          { name: 'session_id', type: 'string', mode: 'nullable', description: 'Session identifier', defaultValue: null },
          { name: 'device_type', type: 'string', mode: 'nullable', description: 'Device type', tags: ['mobile', 'desktop', 'tablet'] },
          { name: 'ip_address', type: 'string', mode: 'nullable', description: 'IP address', tags: ['pii'] },
        ],
        changeLog: [
          { fieldName: 'device_type', changeType: 'added', isBreaking: false, description: 'Added device tracking' },
          { fieldName: 'ip_address', changeType: 'added', isBreaking: false, description: 'Added IP for geolocation' },
        ],
      },
    ],
  },
  {
    id: 'schema-002',
    name: 'Revenue Record Schema',
    subject: 'revenue-record-value',
    description: 'Schema for revenue aggregation records',
    owner: 'finance-data-team',
    team: 'finance',
    format: 'avro',
    currentVersion: 2,
    compatibility: 'full',
    tags: ['revenue', 'finance', 'reporting'],
    usage: {
      producers: 2,
      consumers: 8,
    },
    versions: [
      {
        id: 'ver-002-1',
        version: 1,
        createdAt: '2024-02-01T00:00:00Z',
        createdBy: 'finance.admin@company.com',
        isActive: false,
        compatibility: 'full',
        schema: [
          { name: 'date', type: 'string', mode: 'required', description: 'Date in YYYY-MM-DD format' },
          { name: 'revenue', type: 'double', mode: 'required', description: 'Revenue amount' },
          { name: 'currency', type: 'string', mode: 'required', description: 'Currency code' },
        ],
        changeLog: [],
      },
      {
        id: 'ver-002-2',
        version: 2,
        createdAt: '2024-05-15T00:00:00Z',
        createdBy: 'finance.admin@company.com',
        isActive: true,
        compatibility: 'full',
        schema: [
          { name: 'date', type: 'string', mode: 'required', description: 'Date in YYYY-MM-DD format' },
          { name: 'revenue', type: 'double', mode: 'required', description: 'Revenue amount' },
          { name: 'currency', type: 'string', mode: 'required', description: 'Currency code' },
          { name: 'region', type: 'string', mode: 'nullable', description: 'Region code' },
          { name: 'payment_method', type: 'string', mode: 'nullable', description: 'Payment method' },
        ],
        changeLog: [
          { fieldName: 'region', changeType: 'added', isBreaking: false, description: 'Added regional breakdown' },
          { fieldName: 'payment_method', changeType: 'added', isBreaking: false, description: 'Added payment tracking' },
        ],
      },
    ],
  },
  {
    id: 'schema-003',
    name: 'Customer Profile Schema',
    subject: 'customer-profile-value',
    description: 'Schema for unified customer profile data',
    owner: 'ml-platform-team',
    team: 'ml',
    format: 'protobuf',
    currentVersion: 1,
    compatibility: 'backward',
    tags: ['customer', 'profile', 'ml'],
    usage: {
      producers: 3,
      consumers: 6,
    },
    versions: [
      {
        id: 'ver-003-1',
        version: 1,
        createdAt: '2024-04-01T00:00:00Z',
        createdBy: 'ml.engineer@company.com',
        isActive: true,
        compatibility: 'backward',
        schema: [
          { name: 'customer_id', type: 'string', mode: 'required', description: 'Customer identifier' },
          { name: 'email', type: 'string', mode: 'required', description: 'Email address', tags: ['pii'] },
          { name: 'first_name', type: 'string', mode: 'nullable', description: 'First name', tags: ['pii'] },
          { name: 'last_name', type: 'string', mode: 'nullable', description: 'Last name', tags: ['pii'] },
          { name: 'segment', type: 'string', mode: 'nullable', description: 'Customer segment' },
          { name: 'ltv', type: 'double', mode: 'nullable', description: 'Lifetime value' },
        ],
        changeLog: [],
      },
    ],
  },
  {
    id: 'schema-004',
    name: 'Inventory Update Schema',
    subject: 'inventory-update-value',
    description: 'Schema for real-time inventory updates',
    owner: 'ops-data-team',
    team: 'operations',
    format: 'avro',
    currentVersion: 2,
    compatibility: 'forward',
    tags: ['inventory', 'operations', 'realtime'],
    usage: {
      producers: 8,
      consumers: 4,
    },
    versions: [
      {
        id: 'ver-004-1',
        version: 1,
        createdAt: '2024-01-20T00:00:00Z',
        createdBy: 'ops.admin@company.com',
        isActive: false,
        compatibility: 'forward',
        schema: [
          { name: 'product_id', type: 'string', mode: 'required', description: 'Product SKU' },
          { name: 'warehouse_id', type: 'int', mode: 'required', description: 'Warehouse identifier' },
          { name: 'quantity', type: 'int', mode: 'required', description: 'Available quantity' },
        ],
        changeLog: [],
      },
      {
        id: 'ver-004-2',
        version: 2,
        createdAt: '2024-07-01T00:00:00Z',
        createdBy: 'ops.admin@company.com',
        isActive: true,
        compatibility: 'forward',
        schema: [
          { name: 'product_id', type: 'string', mode: 'required', description: 'Product SKU' },
          { name: 'warehouse_id', type: 'int', mode: 'required', description: 'Warehouse identifier' },
          { name: 'quantity', type: 'int', mode: 'required', description: 'Available quantity' },
          { name: 'reserved_quantity', type: 'int', mode: 'required', description: 'Reserved quantity', defaultValue: 0 },
          { name: 'last_updated', type: 'long', mode: 'required', description: 'Last update timestamp' },
        ],
        changeLog: [
          { fieldName: 'reserved_quantity', changeType: 'added', isBreaking: true, previousMode: 'none', newMode: 'required', description: 'Added reserved quantity tracking' },
          { fieldName: 'last_updated', changeType: 'added', isBreaking: false, description: 'Added timestamp tracking' },
        ],
      },
    ],
  },
  {
    id: 'schema-005',
    name: 'Product Catalog Schema',
    subject: 'product-catalog-value',
    description: 'Schema for product catalog data',
    owner: 'product-data-team',
    team: 'product',
    format: 'json-schema',
    currentVersion: 4,
    compatibility: 'backward',
    tags: ['product', 'catalog', 'ecommerce'],
    usage: {
      producers: 4,
      consumers: 10,
    },
    versions: [
      {
        id: 'ver-005-1',
        version: 1,
        createdAt: '2024-01-10T00:00:00Z',
        createdBy: 'product.admin@company.com',
        isActive: false,
        compatibility: 'backward',
        schema: [
          { name: 'sku', type: 'string', mode: 'required', description: 'Product SKU' },
          { name: 'name', type: 'string', mode: 'required', description: 'Product name' },
          { name: 'price', type: 'double', mode: 'required', description: 'Price' },
        ],
        changeLog: [],
      },
      {
        id: 'ver-005-2',
        version: 2,
        createdAt: '2024-02-15T00:00:00Z',
        createdBy: 'product.admin@company.com',
        isActive: false,
        compatibility: 'backward',
        schema: [
          { name: 'sku', type: 'string', mode: 'required', description: 'Product SKU' },
          { name: 'name', type: 'string', mode: 'required', description: 'Product name' },
          { name: 'price', type: 'double', mode: 'required', description: 'Price' },
          { name: 'category', type: 'string', mode: 'nullable', description: 'Product category' },
        ],
        changeLog: [
          { fieldName: 'category', changeType: 'added', isBreaking: false, description: 'Added category field' },
        ],
      },
      {
        id: 'ver-005-3',
        version: 3,
        createdAt: '2024-04-20T00:00:00Z',
        createdBy: 'product.admin@company.com',
        isActive: false,
        compatibility: 'backward',
        schema: [
          { name: 'sku', type: 'string', mode: 'required', description: 'Product SKU' },
          { name: 'name', type: 'string', mode: 'required', description: 'Product name' },
          { name: 'price', type: 'double', mode: 'required', description: 'Price' },
          { name: 'category', type: 'string', mode: 'nullable', description: 'Product category' },
          { name: 'brand', type: 'string', mode: 'nullable', description: 'Brand name' },
          { name: 'attributes', type: 'map', mode: 'nullable', description: 'Product attributes' },
        ],
        changeLog: [
          { fieldName: 'brand', changeType: 'added', isBreaking: false, description: 'Added brand field' },
          { fieldName: 'attributes', changeType: 'added', isBreaking: false, description: 'Added attributes map' },
        ],
      },
      {
        id: 'ver-005-4',
        version: 4,
        createdAt: '2024-08-01T00:00:00Z',
        createdBy: 'product.admin@company.com',
        isActive: true,
        compatibility: 'backward',
        schema: [
          { name: 'sku', type: 'string', mode: 'required', description: 'Product SKU' },
          { name: 'name', type: 'string', mode: 'required', description: 'Product name' },
          { name: 'price', type: 'double', mode: 'required', description: 'Price' },
          { name: 'category', type: 'string', mode: 'nullable', description: 'Product category' },
          { name: 'brand', type: 'string', mode: 'nullable', description: 'Brand name' },
          { name: 'attributes', type: 'map', mode: 'nullable', description: 'Product attributes' },
          { name: 'images', type: 'array', mode: 'nullable', description: 'Product image URLs' },
          { name: 'status', type: 'string', mode: 'required', description: 'Product status', defaultValue: 'active' },
        ],
        changeLog: [
          { fieldName: 'images', changeType: 'added', isBreaking: false, description: 'Added image URLs' },
          { fieldName: 'status', changeType: 'added', isBreaking: false, description: 'Added product status' },
        ],
      },
    ],
  },
];

export const mockSchemaEvolution: SchemaEvolution[] = [
  {
    schemaId: 'schema-001',
    timeline: [
      { date: '2024-01-15', version: 1, changes: 0, breakingChanges: 0 },
      { date: '2024-03-20', version: 2, changes: 1, breakingChanges: 0 },
      { date: '2024-06-10', version: 3, changes: 2, breakingChanges: 0 },
    ],
  },
  {
    schemaId: 'schema-002',
    timeline: [
      { date: '2024-02-01', version: 1, changes: 0, breakingChanges: 0 },
      { date: '2024-05-15', version: 2, changes: 2, breakingChanges: 0 },
    ],
  },
  {
    schemaId: 'schema-003',
    timeline: [
      { date: '2024-04-01', version: 1, changes: 0, breakingChanges: 0 },
    ],
  },
  {
    schemaId: 'schema-004',
    timeline: [
      { date: '2024-01-20', version: 1, changes: 0, breakingChanges: 0 },
      { date: '2024-07-01', version: 2, changes: 2, breakingChanges: 1 },
    ],
  },
  {
    schemaId: 'schema-005',
    timeline: [
      { date: '2024-01-10', version: 1, changes: 0, breakingChanges: 0 },
      { date: '2024-02-15', version: 2, changes: 1, breakingChanges: 0 },
      { date: '2024-04-20', version: 3, changes: 2, breakingChanges: 0 },
      { date: '2024-08-01', version: 4, changes: 2, breakingChanges: 0 },
    ],
  },
];
