/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as SegmentationRouteImport } from './routes/segmentation'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SchemaRegistryRouteImport } from './routes/schema-registry'
import { Route as QueryPerformanceRouteImport } from './routes/query-performance'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as FreshnessRouteImport } from './routes/freshness'
import { Route as DataMeshRouteImport } from './routes/data-mesh'
import { Route as CostAnalyticsRouteImport } from './routes/cost-analytics'
import { Route as ApiMonitoringRouteImport } from './routes/api-monitoring'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines.index'
import { Route as PipelinesPipelineIdRouteImport } from './routes/pipelines.$pipelineId'

const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentationRoute = SegmentationRouteImport.update({
  id: '/segmentation',
  path: '/segmentation',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRegistryRoute = SchemaRegistryRouteImport.update({
  id: '/schema-registry',
  path: '/schema-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryPerformanceRoute = QueryPerformanceRouteImport.update({
  id: '/query-performance',
  path: '/query-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshnessRoute = FreshnessRouteImport.update({
  id: '/freshness',
  path: '/freshness',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMeshRoute = DataMeshRouteImport.update({
  id: '/data-mesh',
  path: '/data-mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const CostAnalyticsRoute = CostAnalyticsRouteImport.update({
  id: '/cost-analytics',
  path: '/cost-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoringRoute = ApiMonitoringRouteImport.update({
  id: '/api-monitoring',
  path: '/api-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelinesRoute,
} as any)
const PipelinesPipelineIdRoute = PipelinesPipelineIdRouteImport.update({
  id: '/$pipelineId',
  path: '/$pipelineId',
  getParentRoute: () => PipelinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-monitoring': typeof ApiMonitoringRoute
  '/cost-analytics': typeof CostAnalyticsRoute
  '/data-mesh': typeof DataMeshRoute
  '/freshness': typeof FreshnessRoute
  '/incidents': typeof IncidentsRoute
  '/landing': typeof LandingRoute
  '/lineage': typeof LineageRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/query-performance': typeof QueryPerformanceRoute
  '/schema-registry': typeof SchemaRegistryRoute
  '/search': typeof SearchRoute
  '/segmentation': typeof SegmentationRoute
  '/streaming': typeof StreamingRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/pipelines/': typeof PipelinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-monitoring': typeof ApiMonitoringRoute
  '/cost-analytics': typeof CostAnalyticsRoute
  '/data-mesh': typeof DataMeshRoute
  '/freshness': typeof FreshnessRoute
  '/incidents': typeof IncidentsRoute
  '/landing': typeof LandingRoute
  '/lineage': typeof LineageRoute
  '/query-performance': typeof QueryPerformanceRoute
  '/schema-registry': typeof SchemaRegistryRoute
  '/search': typeof SearchRoute
  '/segmentation': typeof SegmentationRoute
  '/streaming': typeof StreamingRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/pipelines': typeof PipelinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-monitoring': typeof ApiMonitoringRoute
  '/cost-analytics': typeof CostAnalyticsRoute
  '/data-mesh': typeof DataMeshRoute
  '/freshness': typeof FreshnessRoute
  '/incidents': typeof IncidentsRoute
  '/landing': typeof LandingRoute
  '/lineage': typeof LineageRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/query-performance': typeof QueryPerformanceRoute
  '/schema-registry': typeof SchemaRegistryRoute
  '/search': typeof SearchRoute
  '/segmentation': typeof SegmentationRoute
  '/streaming': typeof StreamingRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/pipelines/': typeof PipelinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-monitoring'
    | '/cost-analytics'
    | '/data-mesh'
    | '/freshness'
    | '/incidents'
    | '/landing'
    | '/lineage'
    | '/pipelines'
    | '/query-performance'
    | '/schema-registry'
    | '/search'
    | '/segmentation'
    | '/streaming'
    | '/pipelines/$pipelineId'
    | '/pipelines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-monitoring'
    | '/cost-analytics'
    | '/data-mesh'
    | '/freshness'
    | '/incidents'
    | '/landing'
    | '/lineage'
    | '/query-performance'
    | '/schema-registry'
    | '/search'
    | '/segmentation'
    | '/streaming'
    | '/pipelines/$pipelineId'
    | '/pipelines'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-monitoring'
    | '/cost-analytics'
    | '/data-mesh'
    | '/freshness'
    | '/incidents'
    | '/landing'
    | '/lineage'
    | '/pipelines'
    | '/query-performance'
    | '/schema-registry'
    | '/search'
    | '/segmentation'
    | '/streaming'
    | '/pipelines/$pipelineId'
    | '/pipelines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiMonitoringRoute: typeof ApiMonitoringRoute
  CostAnalyticsRoute: typeof CostAnalyticsRoute
  DataMeshRoute: typeof DataMeshRoute
  FreshnessRoute: typeof FreshnessRoute
  IncidentsRoute: typeof IncidentsRoute
  LandingRoute: typeof LandingRoute
  LineageRoute: typeof LineageRoute
  PipelinesRoute: typeof PipelinesRouteWithChildren
  QueryPerformanceRoute: typeof QueryPerformanceRoute
  SchemaRegistryRoute: typeof SchemaRegistryRoute
  SearchRoute: typeof SearchRoute
  SegmentationRoute: typeof SegmentationRoute
  StreamingRoute: typeof StreamingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentation': {
      id: '/segmentation'
      path: '/segmentation'
      fullPath: '/segmentation'
      preLoaderRoute: typeof SegmentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema-registry': {
      id: '/schema-registry'
      path: '/schema-registry'
      fullPath: '/schema-registry'
      preLoaderRoute: typeof SchemaRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-performance': {
      id: '/query-performance'
      path: '/query-performance'
      fullPath: '/query-performance'
      preLoaderRoute: typeof QueryPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freshness': {
      id: '/freshness'
      path: '/freshness'
      fullPath: '/freshness'
      preLoaderRoute: typeof FreshnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-mesh': {
      id: '/data-mesh'
      path: '/data-mesh'
      fullPath: '/data-mesh'
      preLoaderRoute: typeof DataMeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-analytics': {
      id: '/cost-analytics'
      path: '/cost-analytics'
      fullPath: '/cost-analytics'
      preLoaderRoute: typeof CostAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-monitoring': {
      id: '/api-monitoring'
      path: '/api-monitoring'
      fullPath: '/api-monitoring'
      preLoaderRoute: typeof ApiMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof PipelinesRoute
    }
    '/pipelines/$pipelineId': {
      id: '/pipelines/$pipelineId'
      path: '/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof PipelinesPipelineIdRouteImport
      parentRoute: typeof PipelinesRoute
    }
  }
}

interface PipelinesRouteChildren {
  PipelinesPipelineIdRoute: typeof PipelinesPipelineIdRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
}

const PipelinesRouteChildren: PipelinesRouteChildren = {
  PipelinesPipelineIdRoute: PipelinesPipelineIdRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
}

const PipelinesRouteWithChildren = PipelinesRoute._addFileChildren(
  PipelinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiMonitoringRoute: ApiMonitoringRoute,
  CostAnalyticsRoute: CostAnalyticsRoute,
  DataMeshRoute: DataMeshRoute,
  FreshnessRoute: FreshnessRoute,
  IncidentsRoute: IncidentsRoute,
  LandingRoute: LandingRoute,
  LineageRoute: LineageRoute,
  PipelinesRoute: PipelinesRouteWithChildren,
  QueryPerformanceRoute: QueryPerformanceRoute,
  SchemaRegistryRoute: SchemaRegistryRoute,
  SearchRoute: SearchRoute,
  SegmentationRoute: SegmentationRoute,
  StreamingRoute: StreamingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
