/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegmentationRouteImport } from './routes/segmentation'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as FreshnessRouteImport } from './routes/freshness'
import { Route as ApiMonitoringRouteImport } from './routes/api-monitoring'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelinesPipelineIdRouteImport } from './routes/pipelines.$pipelineId'

const SegmentationRoute = SegmentationRouteImport.update({
  id: '/segmentation',
  path: '/segmentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshnessRoute = FreshnessRouteImport.update({
  id: '/freshness',
  path: '/freshness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoringRoute = ApiMonitoringRouteImport.update({
  id: '/api-monitoring',
  path: '/api-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesPipelineIdRoute = PipelinesPipelineIdRouteImport.update({
  id: '/$pipelineId',
  path: '/$pipelineId',
  getParentRoute: () => PipelinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-monitoring': typeof ApiMonitoringRoute
  '/freshness': typeof FreshnessRoute
  '/incidents': typeof IncidentsRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/segmentation': typeof SegmentationRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-monitoring': typeof ApiMonitoringRoute
  '/freshness': typeof FreshnessRoute
  '/incidents': typeof IncidentsRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/segmentation': typeof SegmentationRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-monitoring': typeof ApiMonitoringRoute
  '/freshness': typeof FreshnessRoute
  '/incidents': typeof IncidentsRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/segmentation': typeof SegmentationRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-monitoring'
    | '/freshness'
    | '/incidents'
    | '/pipelines'
    | '/segmentation'
    | '/pipelines/$pipelineId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-monitoring'
    | '/freshness'
    | '/incidents'
    | '/pipelines'
    | '/segmentation'
    | '/pipelines/$pipelineId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-monitoring'
    | '/freshness'
    | '/incidents'
    | '/pipelines'
    | '/segmentation'
    | '/pipelines/$pipelineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiMonitoringRoute: typeof ApiMonitoringRoute
  FreshnessRoute: typeof FreshnessRoute
  IncidentsRoute: typeof IncidentsRoute
  PipelinesRoute: typeof PipelinesRouteWithChildren
  SegmentationRoute: typeof SegmentationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segmentation': {
      id: '/segmentation'
      path: '/segmentation'
      fullPath: '/segmentation'
      preLoaderRoute: typeof SegmentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freshness': {
      id: '/freshness'
      path: '/freshness'
      fullPath: '/freshness'
      preLoaderRoute: typeof FreshnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-monitoring': {
      id: '/api-monitoring'
      path: '/api-monitoring'
      fullPath: '/api-monitoring'
      preLoaderRoute: typeof ApiMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$pipelineId': {
      id: '/pipelines/$pipelineId'
      path: '/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof PipelinesPipelineIdRouteImport
      parentRoute: typeof PipelinesRoute
    }
  }
}

interface PipelinesRouteChildren {
  PipelinesPipelineIdRoute: typeof PipelinesPipelineIdRoute
}

const PipelinesRouteChildren: PipelinesRouteChildren = {
  PipelinesPipelineIdRoute: PipelinesPipelineIdRoute,
}

const PipelinesRouteWithChildren = PipelinesRoute._addFileChildren(
  PipelinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiMonitoringRoute: ApiMonitoringRoute,
  FreshnessRoute: FreshnessRoute,
  IncidentsRoute: IncidentsRoute,
  PipelinesRoute: PipelinesRouteWithChildren,
  SegmentationRoute: SegmentationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
